### PR TITLE
Update USER_leaderboard.js

### PR DESCRIPTION
**Pull request by TechGeekGamer**
You had the `require` looking in the wrong place @tommystefanatic

### CODE REVIEW

**Comment by TechGeekGamer** [comment]
@ tommystefanatic Can you please merge this?

**Comment by tommystefanatic** [comment]
Sure when I get to my MBP

**Comment by TechGeekGamer** [comment]
You should be able to merge from the GitHub app

**Comment by tommystefanatic** [comment]
Merge, squash, or rebase?

**Pull request merged**
